/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nuova.cartella;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {





        Calciatore Ronaldo=new Calciatore("Cristiano","Ronaldo",38,"Attaccante");
        Ronaldo.setGol(815);
        Ronaldo.setPresenze(1118);
        Ronaldo.setSquadra("Manchester United","Civitas Metropolitano");
        Ronaldo.bioCalciatore();

        Calciatore Messi=new Calciatore ("Lionel","Messi",36,"Attaccante");
        Messi.setGol(774);
        Messi.setPresenze(995);
        Messi.setSquadra("PSG","Parco dei Principi");
        Messi.bioCalciatore();

        Messi.setSquadra("Napoli","Stadio Diego Armando Maradona");
        Messi.bioCalciatore();

       




        
    }
}
